// packages/toolbar-vue/src/components/table.vue
<template>
    <div
    data-element="ui"
	class="data-toolbar-table-selector"
	>
        <div class="data-toolbar-table-selector-tr"  v-for="row in currentRows" :key="row">
            <div
            v-for="col in currentCols"
            :class="[{'data-toolbar-table-selector-td': true}, {actived: row - 1 < selectedRows && col - 1 < selectedCols}]"
            :key={col}
            @click="triggerSelect($event,row - 1,col - 1)"
            @mouseover="triggerHover(row - 1,col - 1)"
            />
        </div>
        <div class="data-toolbar-table-selector-info">
            {{selectedRows === undefined ? 0 : selectedRows}}x{{selectedCols === undefined ? 0 : selectedCols}}
        </div>
    </div>
</template>

<script lang="ts">
import { defineComponent, PropType, ref } from 'vue'

export default defineComponent({
    name:"am-table",
    props:{
        maxRows: Number,
        maxCols: Number,
        minRows: Number,
        minCols: Number,
        onSelect: Function as PropType<(event: MouseEvent, rows: number, cols: number) => void>
    },
    setup(props){
        const maxRows = ref(props.maxRows || 10);
        const maxCols = ref(props.maxCols || 10);
        const minRows = ref(props.minRows || 4);
        const minCols = ref(props.minCols || 4);
        const currentRows = ref(4);
        const currentCols = ref(4);
        const selectedRows = ref(0);
        const selectedCols = ref(0); 
        
        return {
            maxRows,
            maxCols,
            minRows,
            minCols,
            currentRows,
            currentCols,
            selectedRows,
            selectedCols
        }
    },
    methods:{
        triggerSelect(event:MouseEvent, rows: number, cols: number){
            if(this.onSelect) this.onSelect(event, rows + 1, cols + 1);
        },
        triggerHover(rows: number, cols: number){
            const showRows = Math.max(this.minRows, Math.min(this.maxRows, rows + 2));
            const showCols = Math.max(this.minCols, Math.min(this.maxCols, cols + 2));
            this.currentRows = showRows
            this.currentCols = showCols
            this.selectedRows = rows + 1
            this.selectedCols = cols + 1
        }
    }
})
</script>
<style>
.data-toolbar-table-selector .data-toolbar-table-selector-tr {
    display: flex;
    flex-wrap: nowrap;
}
.data-toolbar-table-selector .data-toolbar-table-selector-tr .data-toolbar-table-selector-td {
    width: 20px;
    height: 16px;
    border: 1px solid #d9d9d9;
    margin-right: -1px;
    margin-bottom: -1px;
    cursor: pointer;
}
.data-toolbar-table-selector .data-toolbar-table-selector-tr .data-toolbar-table-selector-td.actived {
    background: #ddefff;
}
.data-toolbar-table-selector .data-toolbar-table-selector-info {
    text-align: center;
}
</style>

// packages/toolbar/src/table/index.tsx
import React, { useState } from 'react';
import classnames from 'classnames-es-ts';
import './index.css';

export type Selector = {
	maxRows?: number;
	maxCols?: number;
	minRows?: number;
	minCols?: number;
	onSelect: (event: React.MouseEvent, rows: number, cols: number) => void;
};
const Selector: React.FC<Selector> = props => {
	const [maxRows] = useState(props.maxRows || 10);
	const [maxCols] = useState(props.maxCols || 10);
	const [minRows] = useState(props.minRows || 4);
	const [minCols] = useState(props.minCols || 4);
	const [currentRows, setCurrentRows] = useState(4);
	const [currentCols, setCurrentCols] = useState(4);
	const [selectedRows, setSelectedRows] = useState(0);
	const [selectedCols, setSelectedCols] = useState(0);

	const onSelect = (event: React.MouseEvent, rows: number, cols: number) => {
		props.onSelect(event, rows + 1, cols + 1);
	};

	const onHover = (rows: number, cols: number) => {
		const showRows = Math.max(minRows, Math.min(maxRows, rows + 2));
		const showCols = Math.max(minCols, Math.min(maxCols, cols + 2));

		setCurrentRows(showRows);
		setCurrentCols(showCols);
		setSelectedRows(rows + 1);
		setSelectedCols(cols + 1);
	};

	const renderTr = (row: number, cols: number) => {
		let tds: Array<React.ReactNode> = [];
		const _loop = (col: number) => {
			const cls = classnames({
				'data-toolbar-table-selector-td': true,
				actived: row < selectedRows && col < selectedCols,
			});
			tds.push(
				<div
					className={cls}
					key={col}
					onMouseDown={e => {
						return onSelect(e, row, col);
					}}
					onMouseOver={() => {
						return onHover(row, col);
					}}
				/>,
			);
		};

		for (let c = 0; c < cols; c++) {
			_loop(c);
		}
		return tds;
	};

	const renderTable = (rows: number, cols: number) => {
		let trs = [];
		for (var r = 0; r < rows; r++) {
			trs.push(
				<div className="data-toolbar-table-selector-tr" key={r}>
					{renderTr(r, cols)}
				</div>,
			);
		}
		return trs;
	};

	const rows = selectedRows === undefined ? 0 : selectedRows;
	const cols = selectedCols === undefined ? 0 : selectedCols;
	return (
		<div className="data-toolbar-table-selector" data-element="ui">
			{renderTable(currentRows, currentCols)}
			<div className="data-toolbar-table-selector-info">
				{rows}x{cols}
			</div>
		</div>
	);
};

export default Selector;
