// packages/toolbar/src/button/index.tsx
import React, { useState } from 'react';
import Tooltip from 'antd/es/tooltip';
import classnames from 'classnames-es-ts';
import { formatHotkey, isMobile } from '@aomao/engine';
import type { EngineInterface, Placement } from '@aomao/engine';
import { autoGetHotkey } from '../utils';
import 'antd/es/tooltip/style';
import './index.css';

export type ButtonProps = {
	engine?: EngineInterface;
	name: string;
	icon?: React.ReactNode;
	content?: React.ReactNode | (() => React.ReactNode);
	title?: string;
	placement?: Placement;
	hotkey?: boolean | string;
	command?: { name: string; args: Array<any> } | Array<any>;
	autoExecute?: boolean;
	className?: string;
	active?: boolean;
	disabled?: boolean;
	onClick?: (event: React.MouseEvent) => void | boolean;
	onMouseDown?: (event: React.MouseEvent) => void;
	onMouseEnter?: (event: React.MouseEvent) => void;
	onMouseLeave?: (event: React.MouseEvent) => void;
};

const ToolbarButton: React.FC<ButtonProps> = (props) => {
	const { name, engine, command } = props;

	const [tooltipVisible, setTooltipVisible] = useState(false);

	const onClick = (event: React.MouseEvent) => {
		const { command, onClick, disabled, autoExecute } = props;

		const nodeName = (event.target as Node).nodeName;
		if (nodeName !== 'INPUT' && nodeName !== 'TEXTAREA')
			event.preventDefault();

		if (disabled) return;
		if (onClick && onClick(event) === false) return;
		if (autoExecute !== false) {
			let commandName = name;
			let commandArgs = [];
			if (command) {
				if (!Array.isArray(command)) {
					commandName = command.name;
					commandArgs = command.args;
				} else {
					commandArgs = command;
				}
			}
			engine?.command.execute(commandName, ...commandArgs);
		}
	};

	const onMouseDown = (event: React.MouseEvent) => {
		event.preventDefault();
		const { onMouseDown, disabled } = props;
		if (disabled) return;
		if (onMouseDown) onMouseDown(event);

		setTooltipVisible(false);
	};

	const onMouseEnter = (event: React.MouseEvent) => {
		const { onMouseEnter } = props;
		if (onMouseEnter) {
			onMouseEnter(event);
		}
		setTooltipVisible(true);
	};

	const onMouseLeave = (event: React.MouseEvent) => {
		const { onMouseLeave } = props;
		if (onMouseLeave) {
			onMouseLeave(event);
		}
		setTooltipVisible(false);
	};

	const renderButton = () => {
		const { icon, content, className, active, disabled } = props;
		return (
			<button
				className={classnames('toolbar-button', className, {
					'toolbar-button-active': active,
					'toolbar-button-disabled': disabled,
				})}
				onClick={onClick}
				onMouseDown={onMouseDown}
				onMouseEnter={onMouseEnter}
				onMouseLeave={onMouseLeave}
			>
				{typeof icon === 'string' ? (
					<span className={`data-icon data-icon-${icon}`} />
				) : (
					icon
				)}
				{typeof content === 'function' ? content() : content}
			</button>
		);
	};

	let title = props.title ? (
		<div className="toolbar-tooltip-title">{props.title}</div>
	) : null;
	let hotkey = props.hotkey;
	//默认获取插件的热键
	if (engine && (hotkey === true || hotkey === undefined)) {
		hotkey = autoGetHotkey(
			engine,
			command && !Array.isArray(command) ? command.name : name,
		);
	}
	if (typeof hotkey === 'string' && hotkey !== '') {
		title = (
			<>
				{title}
				<div className="toolbar-tooltip-hotkey">
					{formatHotkey(hotkey)}
				</div>
			</>
		);
	}
	return title && !isMobile ? (
		<Tooltip
			placement={props.placement || 'bottom'}
			title={title}
			visible={tooltipVisible}
		>
			{renderButton()}
		</Tooltip>
	) : (
		renderButton()
	);
};

export default ToolbarButton;

// packages/toolbar-vue/src/components/button.vue
<template>
    <a-tooltip :placement="placement || 'bottom'" :visible="(!!title || !!hotkeyText) && !isMobile ? visible : false">
        <template #title>
            <div v-if="!!title" class="toolbar-tooltip-title">{{title}}</div>
            <div v-if="!!hotkeyText" class="toolbar-tooltip-hotkey" v-html="hotkeyText"></div>
        </template>
        <button 
        :class="['toolbar-button',className,{'toolbar-button-active': active,'toolbar-button-disabled':disabled}]" 
        @click="triggerClick" 
        @mousedown="triggerMouseDown" 
        @mouseenter="triggerMouseEnter" 
        @mouseleave="triggerMouseLeave">
            <slot name="icon"><span v-if="icon" :class="['data-icon',`data-icon-${icon}`]" /></slot>
            <slot>{{typeof content === 'function' ? content() : content}}</slot>
        </button>
    </a-tooltip>
</template>
<script lang="ts">
import { defineComponent, ref} from "vue"
import ATooltip from "ant-design-vue/es/tooltip"
import { formatHotkey, isMobile } from '@aomao/engine'
import { autoGetHotkey } from "../utils"
import { buttonProps } from "../types"
import 'ant-design-vue/es/tooltip/style'

export default defineComponent({
    name:"am-button",
    components:{
        ATooltip
    },
    props:buttonProps,
    setup(props){
        let hotkey = props.hotkey;
        //默认获取插件的热键
        if (props.engine && (hotkey === true || hotkey === undefined)) {
            hotkey = autoGetHotkey(
                props.engine,
                props.command && !Array.isArray(props.command) ? props.command.name : props.name,
            );
        }
        if (typeof hotkey === 'string' && hotkey !== '') {
            hotkey = formatHotkey(hotkey)
        }

        const visible = ref(false)

        return {
            isMobile,
            visible,
            hotkeyText:hotkey
        }
    },
    data(){
        return {
            visible:false
        }
    },
    methods:{
        triggerMouseDown(event:MouseEvent){
            event.preventDefault();
            if (this.disabled) return;
            if (this.onMouseDown) this.onMouseDown(event);
            else {
                event.stopPropagation();
            }
            this.visible = false
        },
        triggerMouseEnter(event:MouseEvent){
            if(this.onMouseEnter) this.onMouseEnter(event)
            this.visible = true
        },
        triggerMouseLeave(event:MouseEvent){
            if(this.onMouseLevel) this.onMouseLevel(event)
            this.visible = false
        },
        triggerClick(event: MouseEvent){
            const nodeName = (event.target as Node).nodeName;
            if (nodeName !== 'INPUT' && nodeName !== 'TEXTAREA')
                event.preventDefault();
            if (this.disabled) return;
            if (this.onClick && this.onClick(event) === false) return;
            if (this.autoExecute !== false) {
                let commandName = this.name;
                let commandArgs = [];
                if (this.command) {
                    if (!Array.isArray(this.command)) {
                        commandName = this.command.name;
                        commandArgs = this.command.args;
                    } else {
                        commandArgs = this.command;
                    }
                }
                this.engine?.command.execute(commandName, ...commandArgs);
            }
        }
    }
})
</script>
<style css>
.editor-toolbar .toolbar-button {
    display: inline-block;
    height: 32px;
    width: auto;
    min-width: 32px;
    margin: 0;
    text-align: center;
    padding: 0 7px;
    background-color: transparent;
    border: 1px solid transparent;
    border-radius: 3px 3px;
    font-size: 16px;
    cursor: pointer;
    color: #595959;
    outline: none;
    line-height: 32px;
}

.editor-toolbar:not(.editor-toolbar-mobile) .toolbar-button {
    padding: 0 4px;
}

.editor-toolbar:not(.editor-toolbar-mobile) .toolbar-button:hover {
    border: 1px solid transparent;
    background-color: #f5f5f5;
}

.editor-toolbar:not(.editor-toolbar-mobile) .toolbar-button:active,.editor-toolbar .toolbar-button-active,.editor-toolbar:not(.editor-toolbar-mobile) .toolbar-button-active:hover {
    background-color: #e8e8e8;
    border: 1px solid transparent;
}

.editor-toolbar .toolbar-button-disabled,.editor-toolbar:not(.editor-toolbar-mobile) .toolbar-button-disabled:hover {
    background-color: transparent;
    border: 1px solid transparent;
    box-shadow: none;
    color: #000000;
    opacity: 0.25;
    cursor: not-allowed;
}
</style>
