// packages/toolbar/src/group/index.tsx
import React from 'react';
import classNames from 'classnames-es-ts';
import { EngineInterface, isMobile } from '@aomao/engine';
import Popover from 'antd/es/popover';
import Button, { ButtonProps } from '../button';
import Dropdown, { DropdownProps } from '../dropdown';
import ColorButton, { ColorButtonProps } from '../color';
import Collapse, { CollapseProps as CollapseButtonProps } from '../collapse';
import 'antd/es/popover/style';
import './index.css';

export type GroupButtonProps = {
	type: 'button';
} & Omit<ButtonProps, 'engine'>;

export type GroupDropdownProps = {
	type: 'dropdown';
} & Omit<DropdownProps, 'engine'>;

export type GroupColorProps = {
	type: 'color';
} & Omit<ColorButtonProps, 'engine'>;

export type CollapseProps = {
	type: 'collapse';
} & Omit<CollapseButtonProps, 'engine'>;

export type GroupProps = {
	engine: EngineInterface;
	items: Array<
		GroupButtonProps | GroupDropdownProps | GroupColorProps | CollapseProps
	>;
	icon?: React.ReactNode;
	content?: React.ReactNode | (() => React.ReactNode);
	popup?: boolean;
};

const ToolbarGroup: React.FC<GroupProps> = ({
	engine,
	items,
	icon,
	content,
	popup,
}) => {
	const renderItems = () => {
		return items.map((item, index) => {
			switch (item.type) {
				case 'button':
					return <Button engine={engine} key={item.name} {...item} />;
				case 'dropdown':
					return (
						<Dropdown engine={engine} key={item.name} {...item} />
					);
				case 'color':
					return (
						<ColorButton
							engine={engine}
							key={item.name}
							{...item}
						/>
					);
				case 'collapse':
					return <Collapse engine={engine} key={index} {...item} />;
			}
		});
	};

	const render = () => {
		if (!!icon || !!content) {
			return (
				<Popover
					getPopupContainer={() =>
						document.querySelector('.editor-toolbar') ||
						document.body
					}
					trigger="click"
					overlayClassName="editor-toolbar-popover"
					content={
						<div
							className={classNames('editor-toolbar', {
								'editor-toolbar-mobile': isMobile && !popup,
								'editor-toolbar-popup': popup,
							})}
							data-element="ui"
						>
							{renderItems()}
						</div>
					}
					arrowPointAtCenter
					placement={isMobile ? 'topRight' : 'bottom'}
				>
					<Button
						name="group-popover"
						icon={icon}
						content={content}
					/>
				</Popover>
			);
		}
		return renderItems();
	};

	return <div className="editor-toolbar-group">{render()}</div>;
};

export default ToolbarGroup;

// packages/toolbar-vue/src/components/group.vue
<template>
    <div v-if="!!icon || !!content" class="editor-toolbar-group">
        <am-popover
        :get-popup-container="getPopupContainer"
        trigger="click"
        overlay-class-name="editor-toolbar-popover"
        :arrow-point-at-center="true"
        :placement="isMobile ? 'topRight' : 'bottom'"
        >
            <template #content>
                <div :class="['editor-toolbar', {'editor-toolbar-mobile': isMobile && !popup,
								'editor-toolbar-popup': popup,}]" data-element="ui">
                    <template v-for="(item , index) in items" :key="index">
                        <am-button v-if="item.type === 'button'" :key="index" v-bind="item" :engine="engine" />
                        <am-dropdown v-if="item.type === 'dropdown'" :key="index" v-bind="item" :engine="engine" />
                        <am-color v-if="item.type === 'color'" :key="index" v-bind="item" :engine="engine" />
                        <am-collapse v-if="item.type === 'collapse'" :key="index" v-bind="item" :engine="engine" />
                    </template>
                </div>
            </template>
            <am-button name="group-popover" :icon="icon" :content="content" />
        </am-popover>
    </div>
    <div class="editor-toolbar-group" v-if="!icon && !content">
        <template v-for="(item , index) in items" :key="index">
            <am-button v-if="item.type === 'button'" :key="index" v-bind="item" :engine="engine" />
            <am-dropdown v-if="item.type === 'dropdown'" :key="index" v-bind="item" :engine="engine" />
            <am-color v-if="item.type === 'color'" :key="index" v-bind="item" :engine="engine" />
            <am-collapse v-if="item.type === 'collapse'" :key="index" v-bind="item" :engine="engine" />
        </template>
    </div>
</template>

<script lang="ts">
import { defineComponent } from 'vue'
import { isMobile } from '@aomao/engine'
import AmPopover from 'ant-design-vue/es/popover'
import AmButton from './button.vue'
import AmDropdown from './dropdown.vue'
import AmColor from './color/color.vue'
import AmCollapse from './collapse/collapse.vue'
import { groupProps } from "../types"
import 'ant-design-vue/es/popover/style'

export default defineComponent({
    name:"am-group",
    components:{
        AmButton,
        AmDropdown,
        AmColor,
        AmCollapse,
        AmPopover
    },
    props:groupProps,
    setup(){
        return {
            isMobile
        }
    },
    methods:{
        getPopupContainer:() => document.querySelector('.editor-toolbar') || document.body
    }
})
</script>
<style>
.editor-toolbar-group {
    padding: 4px 8px;
    width: auto;
    border-left: 1px solid #e8e8e8;
}

.editor-toolbar .editor-toolbar-group:nth-child(1) {
    border-left: none;
}
</style>
