// packages/toolbar/src/color/picker/group.tsx
import React from 'react';
import { EngineInterface } from '@aomao/engine';
import ColorPickerItem from './item';

export type ColorPickerGroupProps = {
	engine: EngineInterface;
	colors: Array<string>;
	activeColors: Array<string>;
	setStroke?: boolean;
	onSelect?: (color: string, event: React.MouseEvent) => void;
};

const ColorPickerGroup: React.FC<ColorPickerGroupProps> = ({
	engine,
	colors,
	activeColors,
	onSelect,
	setStroke,
}) => {
	return (
		<span className="colorpicker-group">
			{colors.map(color => {
				return (
					<ColorPickerItem
						engine={engine}
						color={color}
						key={color}
						activeColors={activeColors}
						onSelect={onSelect}
						setStroke={setStroke}
					/>
				);
			})}
		</span>
	);
};

export default ColorPickerGroup;

// packages/toolbar-vue/src/components/color/picker/group.vue
<template>
    <span class="colorpicker-group">
        <am-color-picker-item v-for="color in colors"
        :engine="engine"
        :color="color.value"
        :active="color.active"
        :key="color.value"
        :on-select="onSelect"
        :set-stroke="setStroke"
        />
    </span>
</template>
<script lang="ts">
import { defineComponent } from 'vue'
import { colorPickerGroupProps } from '../../../types'
import AmColorPickerItem from './item.vue'

export default defineComponent({
    name:"am-color-plicker-group",
    components:{
        AmColorPickerItem
    },
    props:colorPickerGroupProps,
})
</script>
