// packages/toolbar/src/color/picker/index.tsx
import React, { useState } from 'react';
import { EngineInterface } from '@aomao/engine';
import ColorPickerGroup, { ColorPickerGroupProps } from './group';
import Palette from './palette';
import ColorPickerItem from './item';
import './index.css';

export type ColorPickerProps = {
	engine: EngineInterface;
	colors?: Array<Array<string>>;
	defaultColor: string;
	defaultActiveColor: string;
} & Omit<ColorPickerGroupProps, 'colors' | 'activeColors'>;

const ColorPicker: React.FC<ColorPickerProps> = ({
	engine,
	colors,
	defaultActiveColor,
	defaultColor,
	onSelect,
	setStroke,
}) => {
	const [active, setActive] = useState([defaultActiveColor]);
	if (!colors) colors = Palette.getColors();

	const triggerSelect = (color: string, event: React.MouseEvent) => {
		setActive([color]);
		if (onSelect) onSelect(color, event);
	};

	return (
		<div
			className="colorpicker-board"
			onMouseDown={event => {
				if ('INPUT' !== (event.target as Element).tagName) {
					event.preventDefault();
				}
			}}
		>
			<div
				className="colorpicker-default"
				onClick={event => triggerSelect(defaultColor, event)}
			>
				<ColorPickerItem
					engine={engine}
					color={defaultColor}
					activeColors={[]}
					onSelect={triggerSelect}
				/>
				<span className="colorpicker-default-text">
					{engine.language.get(
						'toolbar',
						'colorPicker',
						defaultColor === 'transparent'
							? 'nonFillText'
							: 'defaultText',
					)}
				</span>
			</div>
			{colors.map((data, index) => {
				return (
					<ColorPickerGroup
						engine={engine}
						colors={data}
						key={index}
						activeColors={active}
						onSelect={triggerSelect}
						setStroke={setStroke}
					/>
				);
			})}
		</div>
	);
};

export default ColorPicker;

export { Palette };

// packages/toolbar-vue/src/components/color/picker/picker.vue
<template>
    <div
    class="colorpicker-board"
    @mousedown="triggerMouseDown"
    >
        <div
        class="colorpicker-default"
        @click="triggerSelect(defaultColor,$event)"
        >
            <am-color-picker-item
                :engine="engine"
                :color="defaultColor"
                :active-colors="[]"
                :on-select="triggerSelect"
            />
            <span class="colorpicker-default-text">
                {{text}}
            </span>
        </div>
        <am-color-picker-group
        v-for="(data,index) in colors"
        :engine="engine"
        :colors="data"
        :key="index"
        :on-select="triggerSelect"
        :set-stroke="setStroke"
        />
    </div>
</template>
<script lang="ts">
import { defineComponent, ref } from 'vue'
import { colorPickerProps } from '../../../types'
import AmColorPickerItem from './item.vue'
import AmColorPickerGroup from './group.vue'
import Palette from './palette'

export default defineComponent({
    name:"am-color-picker",
    components:{
        AmColorPickerItem,
        AmColorPickerGroup
    },
    props:colorPickerProps,
    setup(props,cxt){
        const activeColors = (values:Array<Array<string | {value:string,active:boolean}>>,activeValue:string) => {
            return values.map(group => group.map(color => {
                const value = typeof color === "string" ? color : color.value
                return { value, active:activeValue === value }
            }))
        }

        const colors = ref(activeColors(props.colors || Palette.getColors(),props.defaultActiveColor))

        const triggerSelect = (color: string, event: MouseEvent) => {
            colors.value = activeColors(colors.value,color)
            if (props.onSelect) props.onSelect(color, event);
        }
        const text = props.engine.language.get(
                    'toolbar',
                    'colorPicker',
                    props.defaultColor === 'transparent'
                        ? 'nonFillText'
                        : 'defaultText',
                )
        return {
            colors,
            triggerSelect,
            text
        }
    },
    methods:{
        triggerMouseDown(event:MouseEvent){
            if ('INPUT' !== (event.target as Element).tagName) {
                event.preventDefault();
            }
        }
    }
})
</script>
<style>
.colorpicker-default {
    display: flex;
    align-items: center;
    padding: 4px 8px;
    margin: 4px 0 8px;
    border-radius: 2px;
    cursor: pointer;
}

.colorpicker-default:hover {
    background-color: #f5f5f5;
}

.colorpicker-default-text {
    margin-left: 8px; 
}

.colorpicker-group {
    display: flex;
    width: 100%;
    height: auto;
    position: relative;
    padding: 0 8px;
}

.colorpicker-group:nth-child(2){
    margin-bottom: 6px;
}

.colorpicker-group:last-child {
    margin-bottom: 0px;
}

.colorpicker-group-item {
    width: 24px;
    height: 24px;
    padding: 2px 2px;
    display: inline-block;
    border-radius: 3px 3px;
    border: 1px solid transparent;
    flex: 0 0 auto;
    cursor: pointer;
    background-color: #fff;
}
.colorpicker-group-item > span {
    position: relative;
    width: 18px;
    height: 18px;
    display: block;
    border-radius: 2px 2px;
    border: 1px solid transparent;
}
.colorpicker-group-item > span svg {
    position: absolute;
    top: -1px;
    left: 1px;
    width: 12px;
    height: 12px;
}
.colorpicker-group-item-border > span {
    border: 1px solid #e8e8e8;
}
.colorpicker-group-item-special {
    position: relative;
}
.colorpicker-group-item-special:after {
    content: "";
    display: block;
    position: absolute;
    top: 10px;
    left: 0px;
    width: 22px;
    height: 0;
    border-bottom: 2px solid #ff5151;
    transform: rotate(45deg);
}
.colorpicker-group-item:hover {
    border: 1px solid #d9d9d9;
    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.12);
}
</style>
