// plugins/link-vue/src/toolbar/editor.vue
<template>
    <a-config-provider :auto-insert-space-in-button=false>
        <div data-element="ui" :class="['data-link-editor', className]">
            <p>{{textTitle}}</p>
            <p>
                <a-input
                class="data-link-input"
                :value="text"
                :placeholder="textPlaceholder"
                @change="onTextChange($event.target.value)"
                />
            </p>
            <p>{{linkTitle}}</p>
            <p>
                <a-input
                ref="linkRef"
                class="data-link-input"
                :value="link"
                :placeholder="linkPlaceholder"
                @change="onLinkChange($event.target.value)"
                />
            </p>
            <p>
                <a-button
                class="data-link-button"
                @click="onOk(text, link)"
                :disabled="link.trim() === ''"
                >
                    {{buttonTitle}}
                </a-button>
            </p>
        </div>
    </a-config-provider>
</template>
<script lang="ts">
import { defineComponent, onMounted, PropType, ref } from 'vue'
import { LanguageInterface } from '@aomao/engine'
import AConfigProvider from 'ant-design-vue/es/config-provider';
import AInput from 'ant-design-vue/es/input'
import AButton from 'ant-design-vue/es/button'
import 'ant-design-vue/es/input/style';
import 'ant-design-vue/es/button/style';

export default defineComponent({
    name:"am-link-editor",
    components:{
        AConfigProvider,
        AInput,
        AButton
    },
    props:{
        language:{
            type:Object as PropType<LanguageInterface>,
            required:true
        } as const,
        defaultText:String,
        defaultLink:String,
        className:String,
        onLoad:Function as PropType<() => void>,
        onOk:Function as PropType<(text: string, link: string) => void>
    },
    setup(props){
        const text = ref(props.defaultText)
        const link = ref(props.defaultLink)
        const linkRef = ref<HTMLElement | null>(null)
        const textTitle = props.language.get<string>('link', 'text')
        const textPlaceholder = props.language.get<string>('link', 'text_placeholder')

        const linkTitle = props.language.get<string>('link', 'link')
        const linkPlaceholder = props.language.get<string>('link', 'link_placeholder')

        const buttonTitle = props.language.get<string>('link', 'ok_button')

        const onTextChange = (value:string) => {
            text.value = value
        }

        const onLinkChange = (value:string) => {
            link.value = value
        }

        onMounted(() => {
            if (props.onLoad) props.onLoad();
            setTimeout(() => {
              linkRef.value?.focus();
            }, 200);
        })

        return {
            text,
            link,
            textTitle,
            textPlaceholder,
            linkTitle,
            linkPlaceholder,
            buttonTitle,
            onTextChange,
            onLinkChange,
            linkRef
        }
    }
})
</script>

// plugins/link/src/toolbar/editor.tsx
import React, { useEffect, useRef, useState } from 'react';
import { LanguageInterface } from '@aomao/engine';
import Input from 'antd/es/input';
import Button from 'antd/es/button';
import classnames from 'classnames-es-ts';
import 'antd/es/input/style';
import 'antd/es/button/style';

export type LinkEditorProps = {
	language: LanguageInterface;
	defaultText?: string;
	defaultLink?: string;
	className?: string;
	onLoad?: (element: Input) => void;
	onOk: (text: string, link: string) => void;
};

const LinkEditor: React.FC<LinkEditorProps> = ({
	language,
	defaultLink,
	defaultText,
	className,
	onLoad,
	onOk,
}) => {
	const [text, setText] = useState(defaultText || '');
	const [link, setLink] = useState(defaultLink || '');

	const linkRef = useRef<Input>(null);

	useEffect(() => {
		if (onLoad && linkRef.current) onLoad(linkRef.current);
		setTimeout(() => {
			linkRef.current?.focus();
		}, 200);
	}, []);

	return (
		<div className={classnames('data-link-editor', className)}>
			<p>{language.get('link', 'text')}</p>
			<p>
				<Input
					className="data-link-input"
					value={text}
					placeholder={language
						.get('link', 'text_placeholder')
						.toString()}
					onChange={(event) => {
						setText(event.target.value);
					}}
				/>
			</p>
			<p>{language.get('link', 'link')}</p>
			<p>
				<Input
					ref={linkRef}
					className="data-link-input"
					value={link}
					placeholder={language
						.get('link', 'link_placeholder')
						.toString()}
					onChange={(event) => {
						setLink(event.target.value);
					}}
				/>
			</p>
			<p>
				<Button
					className="data-link-button"
					onClick={() => onOk(text, link)}
					disabled={link.trim() === ''}
				>
					{language.get('link', 'ok_button')}
				</Button>
			</p>
		</div>
	);
};

export default LinkEditor;
