// plugins/link/src/toolbar/preview.tsx
import React from 'react';
import classnames from 'classnames-es-ts';
import { Tooltip } from 'antd';
import 'antd/lib/tooltip/style';
import { LanguageInterface } from '@aomao/engine';

export type LinkPreviewProps = {
	language: LanguageInterface;
	href?: string;
	className?: string;
	onEdit: (event: React.MouseEvent) => void;
	onRemove: (event: React.MouseEvent) => void;
};

const LinkPreview: React.FC<LinkPreviewProps> = ({
	language,
	href,
	onEdit,
	onRemove,
}) => {
	return (
		<div className={classnames('data-link-preview')}>
			<Tooltip title={language.get('link', 'link_open')}>
				<a
					className="data-icon data-icon-link data-link-preview-open"
					href={href}
					target="_blank"
				>
					{href}
				</a>
			</Tooltip>
			<Tooltip title={language.get('link', 'link_edit')}>
				<a className="data-icon data-icon-edit" onClick={onEdit} />
			</Tooltip>
			<Tooltip title={language.get('link', 'link_remove')}>
				<a className="data-icon data-icon-unlink" onClick={onRemove} />
			</Tooltip>
		</div>
	);
};

export default LinkPreview;

// plugins/link-vue/src/toolbar/preview.vue
<template>
    <div class="data-link-preview">
        <a-tooltip :title="openTitle">
            <a
            class="data-icon data-icon-link data-link-preview-open"
            :href="href"
            target="_blank"
            >
                {{href}}
            </a>
        </a-tooltip>
        <a-tooltip :title="editTitle">
            <a class="data-icon data-icon-edit" @click="onEdit" />
        </a-tooltip>
        <a-tooltip :title="removeTitle">
            <a class="data-icon data-icon-unlink" @click="onRemove" />
        </a-tooltip>
    </div>
</template>
<script lang="ts">
import { defineComponent, onMounted, PropType } from 'vue'
import { LanguageInterface } from '@aomao/engine'
import ATooltip from 'ant-design-vue/lib/tooltip'
import 'ant-design-vue/lib/tooltip/style/css';

export default defineComponent({
    name:"am-link-preview",
    components:{
        ATooltip
    },
    props:{
        language:{
            type:Object as PropType<LanguageInterface>,
            required:true
        } as const,
        href:String,
        className:String,
        onEdit:Function as PropType<(event:MouseEvent) => void>,
        onRemove:Function as PropType<(event:MouseEvent) => void>,
        onLoad:Function as PropType<() => void>,
    },
    setup(props){
        const openTitle = props.language.get<string>('link', 'link_open')
        const editTitle = props.language.get<string>('link', 'link_edit')
        const removeTitle = props.language.get<string>('link', 'link_remove')

        onMounted(() => {
            if(props.onLoad) props.onLoad()
        })

        return {
            openTitle,
            editTitle,
            removeTitle
        }
    }
})
</script>
